### ISSUE TITLE
Does it support the .net client to get messages from kafka, and these messages are canal written to kafka?

### ISSUE THREAD

**Issue by coldlapy** [CanalClient/CanalSharp#30]
Canal supports protobuf3.0, is there sample code? I'm a newbie, thanks!

**Comment by WithLin** [comment]
Of course, CanalSharp is just a client of canal.
After CanalSharp receives the message, you can write to Kafka, rabbitmq and redis etc.
[sample](https://github.com/CanalClient/CanalSharp/blob/632b82f49c70179af8d8ac9a42ea29879979b3a6/sample/CanalSharp.SimpleClient/Program.cs)
