### ISSUE TITLE
Is need one user which has SUPER privilege on database for CanalSharp ?

### ISSUE THREAD

**Issue by EdisonChou** [CanalClient/CanalSharp#32]
When I use CanalSharp, I found it will not work when my account has no privilege of SUPER (but it has SELECT, REPLICATION SLAVE and REPLICATION CLIENT), that is to say, it can't get message from binlog. 
On the contary, it works when has SUPER permission.
`GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO canal @'%';`
There is one issue about this on Alibaba-Canal project, but I see others said no need the SUPER permission, so I'd like to know is really no need it from your side because it doesn't works on my side.

Reference: https://github.com/alibaba/canal/issues/1323

**Comment by stulzq** [comment]
No SUPER required.This sql is OK.

````sql
CREATE USER canal IDENTIFIED BY 'canal';  
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';
FLUSH PRIVILEGES;
````
I also set this up in a production environment.You can check if it is caused by the binlog setting.

**Comment by EdisonChou** [comment]
Thanks, but it still doesn't work without SUPER permission. So I put aside it at this moment to save some time and continue developing firstly.
I have been forked CanalShrp, thanks for your reply again.
